### PR TITLE
Create category

### PR DESCRIPTION
**Pull request by Riajyuu**

### CODE REVIEW

**Comment by gloomy-ghost** [comment]
Should we separate the changes of exclusion rules to another PR? I prefer a workflow that takes advantages of Git branches :)

**Comment by Riajyuu** [comment]
@gloomy-ghost you are encouraged but not required to do that: markdown article is really unlikely to introduce bugs.

**Comment by gloomy-ghost** [comment]
We can still benefit from it by having a clearer history though...

**Review by gloomy-ghost — APPROVED** [review]

**Review by lrinQVQ — APPROVED** [review]
2333我觉得可以

**Pull request merged**
